### ISSUE TITLE
Instructions would be nice ~.~

### ISSUE THREAD

**Issue by shadowlightwolf89** [dmathieu/heroku-buildpack-jekyll#2]
As the title said, instructions on how to use this would be nice.

**Comment by dmathieu** [comment]
This buildpack is still in very early alpha. Instructions will come later.

**Comment by dmathieu** [comment]
But if you want to dig around, you need to use it in addition to this buildpack: https://github.com/hone/heroku-buildpack-static

**Comment by shadowlightwolf89** [comment]
Okay, thank you, I'll do that.

**Comment by dmathieu** [comment]
Closing. There's been a readme for a while now.
