### ISSUE TITLE
Themes issue

### ISSUE THREAD

**Issue by fosslinux** [dmathieu/heroku-buildpack-jekyll#5]
I created a default jekyll site for testing, build it locally - it worked - and then pushed it and got this error (reproducable):

    remote: Configuration file: /tmp/build_26ee7e8edfc8a4be94254788d3adee60/_config.yml
    remote: bundler: failed to load command: /app/tmp/buildpacks/97ae0d6d26a87fe1847d7dad77ff9b74e7d62e38795199e95afa33b474cb038f9f1ee627afd8f5e1f42c4b8e541295d7889675d835777b897148979253de361e/scripts/precompile (/app/tmp/buildpacks/97ae0d6d26a87fe1847d7dad77ff9b74e7d62e38795199e95afa33b474cb038f9f1ee627afd8f5e1f42c4b8e541295d7889675d835777b897148979253de361e/scripts/precompile)
    remote: Jekyll::Errors::MissingDependencyException: The minima theme could not be found.
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:58:in `rescue in gemspec'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:55:in `gemspec'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:15:in `root'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:50:in `realpath_for'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:45:in `path_for'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:29:in `sass_path'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:37:in `configure_sass'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/theme.rb:9:in `initialize'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:427:in `new'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:427:in `configure_theme'
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:53:in `config='
    remote:   /app/tmp/cache/ruby/2.5.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:24:in `initialize'
    remote:   /app/tmp/buildpacks/97ae0d6d26a87fe1847d7dad77ff9b74e7d62e38795199e95afa33b474cb038f9f1ee627afd8f5e1f42c4b8e541295d7889675d835777b897148979253de361e/scripts/precompile:28:in `new'
    remote:   /app/tmp/buildpacks/97ae0d6d26a87fe1847d7dad77ff9b74e7d62e38795199e95afa33b474cb038f9f1ee627afd8f5e1f42c4b8e541295d7889675d835777b897148979253de361e/scripts/precompile:28:in `<top (required)>'
    remote:  !     Push rejected, failed to compile Static Jekyll app.
    remote:
    remote:  !     Push failed

What do I need to do?

**Comment by dmathieu** [comment]
It looks like jekyll can't find your theme. How did you install that?

**Comment by dmathieu** [comment]
I am going to close this for lack of answer and based on the fact that is't not something that will be fixed within this buildpack.
This error means you're missing some files within your app. My guess is that you need a gem installed. The best way to do that is to use the ruby buildpack on top of the jekyll one (with the right gem specified in Gemfile), write your own buildpack, or fork this one and add your gem to Gemfile.
